### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by stefreak** [syseleven/syselevenstack-documentation#24]
```
$ mkdocs service
Usage: mkdocs [OPTIONS] COMMAND [ARGS]...

Error: No such command "service".
$ mkdocs serve
INFO    -  Building documentation...

Config file 'syselevenstack-documentation/mkdocs.yml' does not exist.
$ cd english/
$ mkdocs serve
INFO    -  Building documentation...
ERROR   -  Config value: 'theme_dir'. Error: The path /usr/share/mkdocs/themes/mkdocs_bootswatch/flatly/ doesn't exist

Aborted with 1 Configuration Errors!
```

So how to actually test the documentation? @LarsFronius maybe you know it?

**Comment by LarsFronius** [comment]
True, the README does not anymore reflect the state of the repository, since we went multi-language.
Short-term fix for you: Change the theme_dir line to theme: flatly in the language subfolder and ```mkdocs serve``` from there.

Long-term fix:
 * Check in the theme to the repository and reference from config. This way, you can ```mkdocs serve``` from both languages, referencing the single sourced theme.
 * we could also think about pulling the whole build/delivery process into a docker container and thus give the development the same environment as production.

**Comment by stefreak** [comment]
Note: for the short term fix you also need to `pip install mkdocs-bootswatch`

**Comment by dschwabeS11** [comment]
Updated README to contain installation notes regarding bootswatch and docu path.
